name: bookingapp
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.16.1 <3.0.0'

dependencies: 
  cloud_firestore: ^3.1.17
  convex_bottom_bar: ^3.0.0
  cupertino_icons: ^1.0.2
  datetime_picker_formfield: ^2.0.0
  dropdown_search: ^2.0.1
  firebase_auth: ^3.3.19
  firebase_core: ^1.17.1
  firebase_messaging: ^11.4.1
  get: ^4.6.1
  http: ^0.13.4
  intl: ^0.17.0
  shared_preferences: 2.0.15
  provider: 6.0.3
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^1.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  assets: 
    - assets/logo/
    - assets/baner/
    - assets/icon/
    - assets/produk/
    - assets/promo/
    - assets/produkH/
  uses-material-design: true

